# fly.toml app configuration file generated for contacts-app on 2023-11-04T22:04:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "contacts-app"
primary_region = "lhr"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  HOST = "0.0.0.0"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
