name: build
on:
  push:
    branches:
      - main
    tags:
      - act*
jobs:
  build:
    runs-on: ubuntu-22.04
    container: golang:1.21.3
    steps:
      - uses: actions/checkout@v4
      - run: make exe.linux
      - uses: actions/upload-artifact@v3
        with:
          name: contacts.linux
          path: contacts.linux
