# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  workflow_dispatch

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: |
        echo "Alice" > /tmp/greeting_name
        export NAME=$(</tmp/greeting_name)
    - name: echo $NAME
      run: echo "Hello $NAME"
