# This is a basic workflow that is manually triggered

name: Manual workflow

on: workflow_dispatch

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Env
        run: |
          cat $GITHUB_ENV
          env
          export NAME="Alice"
          env > $GITHUB_ENV
      - name: Send Greeting
        run: |
          echo "Hello $NAME"
