name: main
on:
  push:
    branches:
      - main
    tags:
      - act*
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: docker run --rm -v "$PWD":/usr/src -w /usr/src golang:1.23.1 make exe.linux
      - run: ls -l
      - uses: actions/upload-artifact@v3
        with:
          name: contacts.linux
          path: contacts.linux
