name: main
on:
  push:
    branches:
      - main
    tags:
      - act*
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - run: make deployable
      - uses: actions/upload-artifact@v3
        with:
          name: contacts.linux
          path: contacts.linux
