name: main
on:
  push:
    branches:
      - main
    tags:
      - act*
jobs:
  build:
    env:
      OUT_DIR: '/tmp/OUTPUT'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: build
        run: |
          make build.linux
      - uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: app
          path: env.OUT_DIR
