name: Release
on:
  push:
    branches:
      - main
    tags:
      - act*
jobs:
  build:
    env:
      OUT_DIR: ${{ github.workspace }}/_OUTPUT
    runs-on: ubuntu-22.04
    steps:
      - name: Checkoug
        uses: actions/checkout@v4
      - name: Setup Go toolchain
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Make
        run: |
          make build.all

          _opstools/octoact_create_release \
            -auth-token ${{ github.token }} \
            -repo-owner ${{ github.repository_owner }} \
            -repo Contacts.app \
            -release-name "Release ${{ github.ref_type }} ${{ github.ref_name }}" \
            -assets-dir ${{ env.OUT_DIR }}

          echo "NEXT"

      - name: Upload Artefact
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: release_files
          path: ${{ env.OUT_DIR }}
