name: Release
on:
  push:
    branches:
      - main
    tags:
      - act*
jobs:
  build:
    permissions:
      contents: write
    env:
      OUT_DIR: ${{ github.workspace }}/_OUTPUT
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Registry Login
        uses: docker/login-action@v3
        with:
          registry: 'registry.digitalocean.com'
          username: ${{ secrets.DIGITALOCEAN_TOKEN }}
          password: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Build
        run: make deployed
